# Generated by Django 4.2.4 on 2023-08-11 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatModel',
            fields=[
                ('id', models.AutoField(db_column='uc_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='uc_name', verbose_name='User Name')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'cb_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConversationChatModel',
            fields=[
                ('id', models.AutoField(db_column='cc_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[(1, 'USER'), (2, 'BOT')], max_length=255)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trailId', models.ForeignKey(db_column='cc_trail', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Conversation_Chat_Model_trailId', to='chat.conversationchatmodel', verbose_name='Trail')),
                ('user', models.ForeignKey(db_column='cc_user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Conversation_Chat_Model_user', to='chat.userchatmodel', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'cb_conversations',
                'managed': True,
            },
        ),
    ]
